In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.corpus import words
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df = pd.read_csv('C:\\Users\\krish\\OneDrive\\Desktop\\Projects\\Email-Classification\\Dataset\\spam_assassin.csv')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3815282457.py, line 1)

In [4]:
df

text  target
0     From ilug-admin@linux.ie Mon Jul 29 11:28:02 2...       0
1     From gort44@excite.com Mon Jun 24 17:54:21 200...       1
2     From fork-admin@xent.com Mon Jul 29 11:39:57 2...       1
3     From dcm123@btamail.net.cn Mon Jun 24 17:49:23...       1
4     From ilug-admin@linux.ie Mon Aug 19 11:02:47 2...       0
...                                                 ...     ...
5791  From ilug-admin@linux.ie Mon Jul 22 18:12:45 2...       0
5792  From fork-admin@xent.com Mon Oct 7 20:37:02 20...       0
5793  Received: from hq.pro-ns.net (localhost [127.0...       1
5794  From razor-users-admin@lists.sourceforge.net T...       0
5795  From rssfeeds@jmason.org Mon Sep 30 13:44:10 2...       0

[5796 rows x 2 columns]

In [5]:
y = df['target']
x = df['text']

to download wordnet from NLTK

In [6]:
import subprocess

# Download and unzip wordnet
try:
    nltk.data.find('wordnet.zip')
except:
    nltk.download('wordnet', download_dir='/kaggle/working/')
    command = "unzip /kaggle/working/corpora/wordnet.zip -d /kaggle/working/corpora"
    subprocess.run(command.split())
    nltk.data.path.append('/kaggle/working/')

# Now you can import the NLTK resources as usual
from nltk.corpus import wordnet

[nltk_data] Downloading package wordnet to /kaggle/working/...
Archive:  /kaggle/working/corpora/wordnet.zip
   creating: /kaggle/working/corpora/wordnet/
  inflating: /kaggle/working/corpora/wordnet/lexnames  
  inflating: /kaggle/working/corpora/wordnet/data.verb  
  inflating: /kaggle/working/corpora/wordnet/index.adv  
  inflating: /kaggle/working/corpora/wordnet/adv.exc  
  inflating: /kaggle/working/corpora/wordnet/index.verb  
  inflating: /kaggle/working/corpora/wordnet/cntlist.rev  
  inflating: /kaggle/working/corpora/wordnet/data.adj  
  inflating: /kaggle/working/corpora/wordnet/index.adj  
  inflating: /kaggle/working/corpora/wordnet/LICENSE  
  inflating: /kaggle/working/corpora/wordnet/citation.bib  
  inflating: /kaggle/working/corpora/wordnet/noun.exc  
  inflating: /kaggle/working/corpora/wordnet/verb.exc  
  inflating: /kaggle/working/corpora/wordnet/README  
  inflating: /kaggle/working/corpora/wordnet/index.sense  
  inflating: /kaggle/working/corpora/wordnet/data.

Below code performs the following tasks:-

1) create a list called emails which will extract each email from X and append it to list

2) for each email in our dataframe X perform following tasks:-

i) Firstly, use the re library in python to substitute the extra characters (which are not a-z or A-Z) by space and then store the new email as an item.

ii) convert the final email into lower case and split into words based on space forming a list, then add only those words which are present in words corpus (to have only general sensible words making our text less precise maybe but cleaner)

iii) for each word, first check if word is stopword or not. if it is not stopword then lemmatize it (convert it to its root form which makes it easier to process and also multiple variations of a word is converted to single form)

iv) Finally, all words are now in root form. Combine them using space and then return the final email

For loop takes so long, create a function that does the processing work and then perform vectorization by converting all raw emails to a list and then calling vector function, storing output in emails list

Due to large processing time, taking sample of only 1000 emails


In [10]:
def process_email(email):
    lm = WordNetLemmatizer() #object of WordNetLemmatizer
    new_email = re.sub('[^a-zA-Z]',' ',str(email)) #whatever is not included in a-z and A-Z, replace with space and convert item to string
    new_email = new_email.lower()
    new_email_words = new_email.split() #convert to lower case throughout then split on space
    #new_email = [word for word in new_email_words if word in set(words.words())] #vectorize this operation
    new_email = [lm.lemmatize(word) for word in new_email_words if word not in set(stopwords.words('english'))] 
    new_email = (' '.join(str(x) for x in new_email))
    return new_email

In [11]:
emails = [] #contains final emails after removing extra characters, stop words and performing lemmatization
numpy_arr_emails = np.array(x,dtype = object)
vect_process_email = np.vectorize(process_email,otypes = [str])
emails = vect_process_email(numpy_arr_emails)

In [12]:
emails[0]

'ilug admin linux ie mon jul return path ilug admin linux ie delivered yyyy localhost netnoteinc com received localhost localhost phobos lab netnoteinc com postfix esmtp id f jm localhost mon jul edt received phobos localhost imap fetchmail jm localhost single drop mon jul ist received lugh tuatha org root lugh tuatha org dogma slashnull org esmtp id g rhn jm ilug jmason org sat jul received lugh root localhost lugh tuatha org esmtp id saa sat jul x authentication warning lugh tuatha org host root localhost claimed lugh received mail mail iol ie mail mail iol ie lugh tuatha org esmtp id saa ilug linux ie sat jul received dialup t cwt esat net helo hobbiton cod ie mail mail iol ie esmtp exim id yvvf w ilug linux ie sat jul received cdaly localhost hobbiton cod ie id g rdroo ilug linux ie sat jul date sat jul conor daly conor daly oceanfree net ilug main list ilug linux ie subject ilug architecture crossover trouble w rh solved message id b hobbiton cod ie mail followup ilug main list il

In [ ]:
emails = list(emails)
y = list(y)
y

In [15]:
processed_emails = pd.DataFrame(emails)
processed_emails.to_csv('processed_emails.csv')

In [ ]:
print(emails[0])

Now, performing bag of words approach to convert text data to numbers using scikit count 

In [9]:
cv = CountVectorizer(ngram_range = (1,2)) # 1,2 implies consider only bigrams at max
test_email = cv.fit_transform(emails).toarray() #perform bag of words then convert it to an array so that its easy to work on
print(len(test_email[0]))

312


Now, trying Term Frequency (TF) and Inverse Document Frequency (IDF) instead to compare

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tiv=TfidfVectorizer()
emails = tiv.fit_transform(emails).toarray()
print(emails[0])

[0. 0. 0. ... 0. 0. 0.]


TF-IDF approach gives lesser number (for this example atleast, check more to confirm)

However, TF-IDF data is highly decimal intensive so normalize the data before training

Performing basic normalization using scikit

In [ ]:
from sklearn import preprocessing
test_email_2 = np.array(test_email_2)
test_email_2 = test_email_2.reshape(1,-1)
normalise_tem2 = preprocessing.normalize(test_email_2)
print(normalise_tem2)

This should be enough for data processing, next step process all input data, perform splitting into train, cv and test set and then build classifier model and evaluate metrics

Normalizing tf-idf array of all emails using min max scaler

In [ ]:
scaler = preprocessing.MinMaxScaler()
test = test_email_2[0].reshape(-1,1)
norm = scaler.fit_transform(test)
print(norm)

splitting data into training and test set (66/33)

In [17]:
from sklearn.model_selection import train_test_split
Email_train, Email_test, Y_train, Y_test = train_test_split(emails, y, test_size = 0.33, random_state = 7)

In [ ]:
Y_test

First testing model without normalizing to see if its needed or not

For classification, following models will be built to perform binary classification and the model with most accuracy will be final:-

1) Random Forest Classifier

2) Decision Trees
 
3) Logistic Regression

4) Naive Bayes Classifier

Random Forest Classifier

In [19]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth = 4,random_state = 0)
clf.fit(Email_train,Y_train)
Y_pred = clf.predict(Email_test)

In [20]:
Y_pred

array([1, 1, 0, ..., 1, 0, 0])

Naive Bayes Classifier

In [23]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()

clf.fit(Email_train,Y_train)
Y_pred = clf.predict(Email_test)

In [24]:
Y_pred

array([1, 1, 1, ..., 1, 0, 1])

Accuracy Metrics - Evaluating our model performance using scikit metrics

In [28]:
from sklearn.metrics import accuracy_score,precision_score,recall_score, classification_report

acc_score = accuracy_score(Y_test,Y_pred)
rep = classification_report(Y_test,Y_pred)

In [29]:
rep

'              precision    recall  f1-score   support\n\n           0       0.98      0.99      0.99      1281\n           1       0.98      0.97      0.97       632\n\n    accuracy                           0.98      1913\n   macro avg       0.98      0.98      0.98      1913\nweighted avg       0.98      0.98      0.98      1913\n'

In [26]:
acc_score

0.9811813904861474

Without Cross Validation

Random Forest Classifier : 83.64

Naive Bayes : 98.12